background {
  monitor-
  blur_passes=1
  blur_size=7
  noise=0.011700
  path=/home/aayush/Pictures/lockscreen.jpg
}


image {
  halign=center
  path=/home/aayush/Pictures/profile.jpg
  position=0, 50
  valign=center
}

input-field {
  size=280,56
  check_color=rgb(30, 107, 204)
  dots_center = true
  dots_size = 0.28
  dots_spacing = 0.45
  fade_on_empty=false
  font_family=JetBrainsMono Nerd Font
  font_color = rgb(205, 214, 244)
  halign=center
  hide_input=false
  inner_color = rgba(20, 20, 30, 0.6)
  outer_color = rgba(0, 0, 0, 0.0)
  check_color = rgb(137, 180, 250)
  fail_color = rgb(243, 139, 168)
  outline_thickness=2
  placeholder_text=<i><span foreground="##cdd6f4">Enter password</span></i>
  position=0, -150
  rounding=-1
  valign=center
}

label {
  color=rgba(242, 243, 244, 0.75)
  font_family=JetBrainsMono Nerd Font
  font_size=95
  halign=center
  position=0, 300
  text=$TIME
  valign=center
}

label {
  color=rgba(242, 243, 244, 0.75)
  font_family=JetBrainsMono Nerd Font
  font_size=22
  halign=center
  position=0, 200
  text=cmd[update:1000] echo $(date +"%A, %B %d")
  valign=center
}

label {
  text = $USER
  font_family = JetBrainsMono Nerd Font
  font_size = 22

  color = rgb(205, 214, 244)

  halign = center
  valign = center
  position = 0, -60
}
