hl.on("hyprland.start", function()
    hl.exec_cmd("quickshell")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("xrdb -merge ~/.Xresources")
    hl.exec_cmd("hyprsession -m load-and-exit")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("eval $(gnome-keyring-daemon --start --components=secrets)")
end)
