hl.on("hyprland.start", function()
    hl.exec_cmd("quickshell")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    -- hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("hyprsession -m load-and-exit")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("chromium --class=whatsapp-pwa --wayland-app-id=whatsapp-pwa --user-data-dir=$HOME/.local/share/chromium-whatsapp-pwa --app=https://web.whatsapp.com --no-first-run --no-default-browser-check --disable-sync --disable-default-apps --disable-extensions --disable-component-extensions-with-background-pages --disable-background-mode --disable-search-engine-choice-screen --disable-background-networking --disable-client-side-phishing-detection --disable-domain-reliability --disable-breakpad --disable-crash-reporter --metrics-recording-only --disable-features=Translate,AutofillServerCommunication,MediaRouter,OptimizationHints,InterestFeedContentSuggestions,PrivacySandboxSettings4")
end)
